### ISSUE TITLE
What is the botton for screen sharing? What is the advantage over using web directly?

### ISSUE THREAD

**Issue by NanyangTaiji** [ashiqursuperfly/AndroidEasyVidChat#3]

**Comment by ashiqursuperfly** [comment]
**Screen Share**
Just enable the screencapture config before starting the videocall activity:
```
VidChatConfig.screenCaptureEnabled = true
startActivityForResult(VidChat.getCallingIntent(activity, roomID), CALL_REQUEST_CODE) // send an unique roomID for your call, the receiver user must also connect on the same roomID
```
**Advantage**
Well, the reason i built this library is primarily because all webRTC providers are paid. e.g: I really liked twillio or openTok. But, i really needed something really quick and simple mainly for 'prototyping'. Needless to say, the paid webRTC providers give much more stable output, however for my use case its doing perfectly fine for free up to now. The experience can be improved and im still working on it. Contributions are welcome too. <3

**Comment by NanyangTaiji** [comment]
Thanks for your explanation. Just did not see the relevant button in your demo.  I find that, so long as the unique room ID is known to the intended receiver,  he can chat with you directly from Web browser without this app. And you can initiate the call from Web directly as well, right?

**Comment by ashiqursuperfly** [comment]
Yeah, just need to send the roomID to the receiver. And, the receiver can use either the browser or the app. And yes you can do vice versa as well.

**Comment by NanyangTaiji** [comment]
So this is my question. Both sides can initiate the chat by Web, what is the unique advantage with this app?
